# Generated by Django 3.1.4 on 2020-12-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201224_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='default_phone_number',
        ),
    ]
