# Generated by Django 3.1.4 on 2020-12-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201224_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_passport_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
