# Generated by Django 3.1.4 on 2020-12-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_default_passport_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_passport_no',
            new_name='default_passport_num',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_phone_number',
            new_name='default_phone_num',
        ),
    ]
