# Generated by Django 3.1.4 on 2021-01-19 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201229_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_passport_num',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9, message='Does not meet the required             length')]),
        ),
    ]
