# Generated by Django 3.1.4 on 2020-12-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201224_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='order_total',
        ),
    ]
