# Generated by Django 3.1.4 on 2020-12-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20201224_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='full_name',
        ),
    ]
