# Generated by Django 3.1.4 on 2020-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_destination_addons'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='trip_addons',
            field=models.ManyToManyField(blank=True, to='products.AddOn'),
        ),
    ]
