# Generated by Django 3.1.4 on 2020-12-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_ref',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
