# Generated by Django 3.1.4 on 2020-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_trip_trip_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_ref',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
