# Generated by Django 3.1.3 on 2020-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20201124_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='is_leaduser',
            field=models.BooleanField(default=False),
        ),
    ]
