# Generated by Django 3.1.4 on 2020-12-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20201224_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('OPENED', 'Open'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='OPENED', max_length=10),
        ),
    ]
