# Generated by Django 3.1.4 on 2020-12-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20201224_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='is_leaduser',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
