# Generated by Django 3.1.4 on 2021-01-19 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20201229_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='passport_no',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9, message='Does not meet the required             length')]),
        ),
    ]
