# Generated by Django 3.1.4 on 2020-12-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20201214_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.trip'),
        ),
    ]
