# Generated by Django 3.1.4 on 2020-12-02 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('bookings', '0003_passenger_is_leaduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='profiles.userprofile'),
        ),
    ]
