# Generated by Django 3.1.4 on 2020-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_lead_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'initial'), ('RESERVED', 'Reserved'), ('COMPLETE', 'Complete')], default='INITIAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stripe_pid',
            field=models.CharField(default='0', max_length=254),
        ),
    ]
