# Generated by Django 3.1.4 on 2021-01-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20210119_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
