# Generated by Django 3.1.4 on 2021-01-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20210124_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
