# Generated by Django 3.1.4 on 2021-01-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20210124_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='lead_passenger',
            new_name='lead_user',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='is_leaduser',
            new_name='is_leadpassenger',
        ),
    ]
