# Generated by Django 3.1.4 on 2020-12-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20201204_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('COMPLETE', 'Complete')], default='RESERVED', max_length=10),
        ),
    ]
