# Generated by Django 3.1.4 on 2020-12-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20201206_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='num_passengers',
        ),
    ]
