# Generated by Django 3.1.4 on 2020-12-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_booking_num_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('COMPLETE', 'Complete')], default='INITIAL', max_length=10),
        ),
    ]
