# Generated by Django 3.1.4 on 2020-12-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20201206_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('RESERVED', 'Reserved'), ('COMPLETE', 'Complete')], default='INITIAL', max_length=10),
        ),
    ]
