# Generated by Django 3.1.3 on 2020-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='min_medical_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
