# Generated by Django 3.1.3 on 2020-11-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201116_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('max_passengers', models.IntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True)),
                ('min_medical_threshold', models.IntegerField(default=0)),
            ],
            bases=('products.product',),
        ),
    ]
