# Generated by Django 3.1.3 on 2020-11-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201117_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
