# Generated by Django 3.1.3 on 2020-11-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='seats_available',
            field=models.IntegerField(editable=False),
        ),
    ]
