# Generated by Django 3.1.3 on 2020-11-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201118_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
